'use client';

import { useEffect, useState } from 'react';
import { type ShowFiles, loadTemplate, readShowFiles } from '@/lib/browser';
import { loadBlankShow } from '@/lib/gma1/blank/blank';
import { Button, FileButton, Section } from './ui';

export function LoadPanel({ onOpen }: { onOpen: (files: ShowFiles, fromTemplate: boolean) => void }) {
  const [template, setTemplate] = useState<ShowFiles | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    loadTemplate().then(setTemplate);
  }, []);

  return (
    <div className="grid gap-4 md:grid-cols-2">
      <Section title="Open an existing show">
        <p className="mb-4 text-sm text-zinc-600 dark:text-zinc-400">
          Select the archive of a gma1 show (version 6.x): <code>name.tar.gz</code> — and optionally its
          <code>name.sho</code> too. They are read in this browser only.
        </p>
        <FileButton
          label="Choose show files…"
          accept=".sho,.gz"
          multiple
          variant="primary"
          onFiles={async (files) => {
            setError(null);
            try {
              onOpen(await readShowFiles(files), false);
            } catch (e) {
              setError((e as Error).message);
            }
          }}
        />
        {error && <p className="mt-3 text-sm text-red-600">{error}</p>}
      </Section>

      <Section title="Start from scratch">
        <p className="mb-3 text-sm text-zinc-600 dark:text-zinc-400">
          Creates an empty show (file version 6.6) with the standard attributes, so you can add fixture
          types and patch straight away. This blank show is generated by the app and has not been verified
          on a real console — load it once in gma1 onPC to confirm before relying on it.
        </p>
        <Button
          variant="primary"
          onClick={async () => {
            setError(null);
            try {
              onOpen(await loadBlankShow('New Show'), true);
            } catch (e) {
              setError(`Could not load the empty show: ${(e as Error).message}`);
            }
          }}
        >
          New empty show
        </Button>
        {template && (
          <div className="mt-4 border-t border-zinc-200 pt-3 dark:border-zinc-800">
            <p className="mb-2 text-sm text-zinc-600 dark:text-zinc-400">
              Or start from a blank show you saved from your own console (guaranteed to load there):
            </p>
            <Button onClick={() => onOpen(template, true)}>New show from “{template.baseName}”</Button>
          </div>
        )}
      </Section>
    </div>
  );
}
