import type { ShowFiles } from '../../browser';
import { basePath } from '../../basePath';

/**
 * Load the bundled empty gma1 show (the only bundled binary show artifact). It contains
 * no show content: the fixture, DMX, group, preset, cue, effect and view pools are empty; it carries
 * the standard attribute vocabulary so fixture types and fixtures can be added. Generated by the
 * project (see docs/FORMAT.md) — not verified on real hardware; confirm in gma1 onPC before use.
 */
export async function loadBlankShow(baseName = 'New Show'): Promise<ShowFiles> {
  const dir = `${basePath}/blank/New%20Show`;
  const [sho, tgz] = await Promise.all([
    fetch(`${dir}.sho`).then((r) => r.arrayBuffer()),
    fetch(`${dir}.tar.gz`).then((r) => r.arrayBuffer()),
  ]);
  return { baseName, sho: new Uint8Array(sho), tgz: new Uint8Array(tgz) };
}
